### ISSUE TITLE
Translation of Cancel and Save buttons

### ISSUE THREAD

**Issue by jherkel** [hayzey/md-rainbow#11]
Could you merge this pull request (if it is possible)?
https://github.com/brianpkelley/md-color-picker/pull/109

**Comment by hayzey** [comment]
@jherkel Could you make a pull request with the changes you want? There seems to be a lot of code in that PR that is unrelated to those text bindings. If you could make a PR with only the code related to the `okText` and `cancelText` bindings, I'd be happy to merge it 😄

**Comment by hayzey** [comment]
@jherkel I've merged your PR and made a new release - version `1.1.0`.

**Comment by jherkel** [comment]
I have tried to use a new version 1.1.0 but there is a problem because dist directory still contains old version.Could you also sync dist directory?

**Comment by hayzey** [comment]
@jherkel Oops, my bad. I'll fix that up right away. Thanks for letting me know.

**Comment by hayzey** [comment]
@jherkel I rebuilt `dist/` and released a new version - `1.1.1`

Let me know if there are any problems.
